apiVersion: batch/v1
kind: CronJob
metadata:
  name: oneshot
spec:
  scedule: "*/1 * * * *"
  template:
    spec:
      completions: 3
      parallelism: 3
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue
        imagePullPolicy: Always
        args:
        - "--keygen-enable"
        - "--keygen-exit-on-complete"
        - "--keygen-num-to-gen=10"
      restartPolicy: OnFailure