apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx    
      ports:
        - containerPort: 8080
  readinessProbe:
    httpGet:
      path: /api/ready
      port: 8080      
    initialDelaySeconds: 
    periodSeconds:  